In [2]:
# Array slicing: Accessing Subarrays

In [3]:
import numpy as np

In [4]:
## One-dimensional subarrays

In [5]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
# First five elements
x[:5]

array([0, 1, 2, 3, 4])

In [7]:
x[::5] # Every other element

array([0, 5])

In [8]:
x[1::5] # Every other element starting at index 1

array([1, 6])

In [9]:
x[::-1] # all elements are reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [10]:
x[5::-2] # reverse every other from index five

array([5, 3, 1])

In [11]:
## Multidimensional subarrays
x1 = np.random.randint(0, 10, (3, 4))
x1

array([[5, 6, 5, 1],
       [2, 2, 1, 9],
       [2, 0, 7, 0]])

In [12]:
x1[:3, ::2] # all rows, every other column

array([[5, 5],
       [2, 1],
       [2, 7]])

In [13]:
# reversing arrays
x1[::1, ::-1]

array([[1, 5, 6, 5],
       [9, 1, 2, 2],
       [0, 7, 0, 2]])

In [14]:
## Accessing arrays rows amd columns

In [15]:
x1[:, 0] # first column

array([5, 2, 2])

In [16]:
x1[0, :] # first row
x1[0]

array([5, 6, 5, 1])

In [17]:
## Reshaping arrays

In [21]:
grid = np.arange(1, 10).reshape((3, 3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
x = np.array([1, 2, 3])

# ro vector via reshape
x.reshape(1, 3)

array([[1, 2, 3]])

In [25]:
# row vector via newaxis
x[np.newaxis, :]

array([[1, 2, 3]])

In [26]:
# comun vecor via reshape
x.reshape(3, 1)

array([[1],
       [2],
       [3]])

In [29]:
# column vector via new axis
z[:, np.newaxis]

NameError: name 'z' is not defined