In [1]:
# Array slicing: Accessing Subarrays

In [2]:
import numpy as np

In [3]:
## One-dimensional subarrays

In [4]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# First five elements
x[:5]

array([0, 1, 2, 3, 4])

In [13]:
x[::5] # Every other element

array([0, 5])

In [11]:
x[1::5] # Every other element starting at index 1

array([1, 6])

In [14]:
x[::-1] # all elements are reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [17]:
x[5::-2] # reverse every other from index five

array([5, 3, 1])

In [27]:
## Multidimensional subarrays
x1 = np.random.randint(0, 10, (3, 4))
x1

array([[1, 4, 2, 0],
       [8, 0, 6, 7],
       [8, 3, 5, 9]])

In [30]:
x1[:3, ::2] # all rows, every other column

array([[1, 2],
       [8, 6],
       [8, 5]])

In [31]:
# reversing arrays
x1[::1, ::-1]

array([[0, 2, 4, 1],
       [7, 6, 0, 8],
       [9, 5, 3, 8]])

In [32]:
## Accessing arrays rows amd columns

In [34]:
x1[:, 0] # first column

array([1, 8, 8])

In [38]:
x1[0, :] # first row
x1[0]

ommitted [1 4 2 0]
