In [2]:
# Array slicing: Accessing Subarrays

In [3]:
import numpy as np

In [4]:
## One-dimensional subarrays

In [5]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
# First five elements
x[:5]

array([0, 1, 2, 3, 4])

In [7]:
x[::5] # Every other element

array([0, 5])

In [8]:
x[1::5] # Every other element starting at index 1

array([1, 6])

In [9]:
x[::-1] # all elements are reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [10]:
x[5::-2] # reverse every other from index five

array([5, 3, 1])

In [11]:
## Multidimensional subarrays
x1 = np.random.randint(0, 10, (3, 4))
x1

array([[3, 8, 3, 1],
       [1, 4, 0, 9],
       [7, 1, 2, 7]])

In [12]:
x1[:3, ::2] # all rows, every other column

array([[3, 3],
       [1, 0],
       [7, 2]])

In [13]:
# reversing arrays
x1[::1, ::-1]

array([[1, 3, 8, 3],
       [9, 0, 4, 1],
       [7, 2, 1, 7]])

In [14]:
## Accessing arrays rows amd columns

In [15]:
x1[:, 0] # first column

array([3, 1, 7])

In [16]:
x1[0, :] # first row
x1[0]

array([3, 8, 3, 1])

In [17]:
## Reshaping arrays

In [18]:
grid = np.arange(1, 10).reshape((3, 3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
x = np.array([1, 2, 3])

# ro vector via reshape
x.reshape(1, 3)

array([[1, 2, 3]])

In [20]:
# row vector via newaxis
x[np.newaxis, :]

array([[1, 2, 3]])

In [21]:
# comun vecor via reshape
x.reshape(3, 1)

array([[1],
       [2],
       [3]])

In [22]:
# column vector via new axis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [24]:
## Array Concatenation and Splitting
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [28]:
## Concatinating more thn two arrays
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [29]:
## concatenate two dimensional arrays
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
np.concatenate([grid, grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [30]:
## concatenate along the second axix(zero indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [31]:
## working with mixed arrays
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [32]:
np.hstack([x, grid])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)