In [1]:
import numpy as np

In [2]:
# Create a length-10 integer filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [3]:
# create a 3x5 floating-point array filled with 1s
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [4]:
# create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [5]:
# Create an array filled with a linear sequence
# starting at 0 ending at 20, stepping by 2
# (this is similar to the built in range)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
# Create an array of 5 values evenly spaced between 0 and 10
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [7]:
# create a 4x4array of uniformly distributed
# random values between 0 and 2
np.random.random((4, 4))

array([[0.14379982, 0.23417884, 0.93566378, 0.34023813],
       [0.85137333, 0.47602993, 0.75118541, 0.78510306],
       [0.72658033, 0.81387765, 0.28880206, 0.01655139],
       [0.82120835, 0.31033765, 0.85322479, 0.79859026]])

In [8]:
# create a 4x4 array of normally distributed random values 
# with a mean 2 and standard deviation 1
np.random.normal(2, 1, (3, 3))

array([[1.68674222, 1.82593669, 3.02645514],
       [2.42356092, 2.25410958, 2.80876402],
       [2.14335876, 2.29552384, 0.98265257]])

In [9]:
# create a 4x4 array of random integers in the interval [0, 10]
np.random.randint(0, 10, (4, 4))

array([[2, 6, 1, 2],
       [0, 4, 7, 5],
       [9, 7, 2, 5],
       [2, 2, 3, 8]])

In [10]:
# create a 4x4 identity matrix
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
# create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory loctaion
np.empty(3)

array([1.30771509e-316, 2.12199579e-314, 1.58101007e-322])