In [2]:
## Structured Data: NumPy’s Structured Arrays

In [3]:
import numpy as np

In [4]:
name = ["Alice", "Bob", "Cathy", "Doug"]
age = [25, 45, 37, 19]
weight = [55.0, 85.5, 68, 61.5]

In [7]:
data = np.zeros(4, dtype={'names' : ('name', 'age', 'weight'),
                          'formats' : ('U10', 'i4', 'f8')})
print(data.dtype)

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]


In [8]:
data['name'] = name
data['age'] = age
data['weight'] = weight
print(data)

[('Alice', 25, 55. ) ('Bob', 45, 85.5) ('Cathy', 37, 68. )
 ('Doug', 19, 61.5)]


In [9]:
data['name']

array(['Alice', 'Bob', 'Cathy', 'Doug'], dtype='<U10')

In [10]:
data[0]

('Alice', 25, 55.)

In [11]:
data['age']

array([25, 45, 37, 19], dtype=int32)

In [13]:
data[-1]['name']

'Doug'

In [14]:
# get names where age is under 30
data[data['age'] <30]['name']

array(['Alice', 'Doug'], dtype='<U10')

In [16]:
## More Advanced Compound Types
tp = np.dtype([('id', 'i8'), ('mat', 'f8', (3, 3))])
X = np.zeros(1, dtype=tp)
print(X[0])
print(X['mat'][0])

(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
