In [1]:
# Array slicing: Accessing Subarrays

In [2]:
import numpy as np

In [3]:
## One-dimensional subarrays

In [4]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# First five elements
x[:5]

array([0, 1, 2, 3, 4])

In [6]:
x[::5] # Every other element

array([0, 5])

In [7]:
x[1::5] # Every other element starting at index 1

array([1, 6])

In [8]:
x[::-1] # all elements are reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [9]:
x[5::-2] # reverse every other from index five

array([5, 3, 1])

In [10]:
## Multidimensional subarrays
x1 = np.random.randint(0, 10, (3, 4))
x1

array([[7, 3, 4, 6],
       [5, 1, 5, 2],
       [4, 6, 4, 3]])

In [11]:
x1[:3, ::2] # all rows, every other column

array([[7, 4],
       [5, 5],
       [4, 4]])

In [12]:
# reversing arrays
x1[::1, ::-1]

array([[6, 4, 3, 7],
       [2, 5, 1, 5],
       [3, 4, 6, 4]])

In [13]:
## Accessing arrays rows amd columns

In [14]:
x1[:, 0] # first column

array([7, 5, 4])

In [15]:
x1[0, :] # first row
x1[0]

array([7, 3, 4, 6])

In [16]:
## Reshaping arrays

In [17]:
grid = np.arange(1, 10).reshape((3, 3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
x = np.array([1, 2, 3])

# ro vector via reshape
x.reshape(1, 3)

array([[1, 2, 3]])

In [19]:
# row vector via newaxis
x[np.newaxis, :]

array([[1, 2, 3]])

In [20]:
# comun vecor via reshape
x.reshape(3, 1)

array([[1],
       [2],
       [3]])

In [21]:
# column vector via new axis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [22]:
## Array Concatenation and Splitting
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [23]:
## Concatinating more thn two arrays
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [24]:
## concatenate two dimensional arrays
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
np.concatenate([grid, grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [25]:
## concatenate along the second axix(zero indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [26]:
## working with mixed arrays
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [27]:
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [28]:
## splitting of arrays
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [29]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [30]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [31]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
