In [5]:
## Summing the values in array
import numpy as np
L = np.random.random(100)
sum(L)

54.72481146529171

In [6]:
np.sum(L)

54.72481146529171

In [7]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

123 ms ± 3.58 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
431 µs ± 10.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [8]:
## Minimum and Maximum
min(big_array), max(big_array)

(2.3778817115349682e-07, 0.9999993653434238)

In [9]:
np.min(big_array), np.max(big_array)

(2.3778817115349682e-07, 0.9999993653434238)

In [10]:
big_array.min()

2.3778817115349682e-07

In [11]:
 big_array.max()

0.9999993653434238

In [12]:
### Multidimensional Aggregates
M = np.random.random((3, 4))
print(M)

[[0.48529432 0.2841779  0.61492097 0.72007863]
 [0.99357861 0.67268486 0.45140599 0.32517668]
 [0.49082051 0.65978185 0.1869348  0.76070427]]


In [13]:
M.sum()

6.645559384783093

In [14]:
M.min(axis=0)

array([0.48529432, 0.2841779 , 0.1869348 , 0.32517668])

In [15]:
M.max(axis=1)

array([0.72007863, 0.99357861, 0.76070427])

In [16]:
## Examples
!head -10 data/presidents.csv

order,name,height(cm)
1,George Washington,189
2,John Adams,170
3,Thomas Jefferson,189
4,James Madison,163
5,James Monroe,183
6,John Quincy Adams,171
7,Andrew Jackson,185
8,Martin Van Buren,168
9,William Henry Harrison,173


In [17]:
import pandas as pd
data = pd.read_csv('data/presidents.csv')
heights = np.array(data['height(cm)'])
print(heights)

[189 170 189 163 183 171 185 168 173 183 173 173 175 178 183 193 178 173
 174 183 183 168 170 178 182 180 183 178 182 188 175 179 183 193 182 183
 177 185 188 188 182 185]


In [23]:
print("Mean:          ", heights.mean())
print("Standard deviation:", heights.std())
print("Min height: ", heights.min())
print("Min height: ", heights.max())

Mean:           179.73809523809524
Standard deviation: 6.931843442745892
Min height:  163
Min height:  193


In [27]:
print("25th percentile:  ", np.percentile(heights, 25))
print("Median:           ", np.median(heights))
print("75th percentile   ", np.percentile(heights, 75))

25th percentile:   174.25
Median:            182.0
75th percentile    183.0


In [31]:
%matplotlib inline
import matplotlib.pyplot as plt
import seasborn; seaborn.set()

ModuleNotFoundError: No module named 'seasborn'