In [1]:
## Summing the values in array
import numpy as np
L = np.random.random(100)
sum(L)

50.7893145796208

In [2]:
np.sum(L)

50.78931457962079

In [5]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

126 ms ± 898 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
411 µs ± 5.92 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [6]:
## Minimum and Maximum
min(big_array), max(big_array)

(2.905404486996943e-07, 0.999999657971859)

In [7]:
np.min(big_array), np.max(big_array)

(2.905404486996943e-07, 0.999999657971859)

In [10]:
big_array.min()

2.905404486996943e-07

In [11]:
 big_array.max()

0.999999657971859

In [14]:
### Multidimensional Aggregates
M = np.random.random((3, 4))
print(M)

[[0.23961961 0.83474413 0.02113816 0.7089511 ]
 [0.3813919  0.89009633 0.43112754 0.14138693]
 [0.19591429 0.75320772 0.45806332 0.35515037]]


In [15]:
M.sum()

5.410791416640781

In [16]:
M.min(axis=0)

array([0.19591429, 0.75320772, 0.02113816, 0.14138693])

In [17]:
M.max(axis=1)

array([0.83474413, 0.89009633, 0.75320772])