In [5]:
## Introducing Broadcasting
import numpy as np
a = np.array([7, 1, 2])
b = np.array([5, 5, 5])
a + b

array([12,  6,  7])

In [6]:
a + 5

array([12,  6,  7])

In [7]:
M = np.ones((3, 3))
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
M + a

array([[8., 2., 3.],
       [8., 2., 3.],
       [8., 2., 3.]])

In [10]:
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]
print(a)
print(b)

[0 1 2]
[[0]
 [1]
 [2]]


In [11]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [14]:
np.arange(3) + np.ones((3,3))

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [16]:
## Rules o braodcasting
## Example 1 Adding two dimensional array to one-dem
M = np.ones((2,3))
a = np.arange(3)
M + a

array([[1., 2., 3.],
       [1., 2., 3.]])

In [18]:
# Example 2 Array need to be broadcast
a = np.arange(3).reshape((3, 1))
b = np.arange(3)

In [21]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [22]:
# Example 3
M = np.ones((3, 2))
a = np.arange(3)

In [26]:
a[:, np.newaxis].shape

(3, 1)

In [27]:
M + a[:, np.newaxis].shape

array([[4., 2.],
       [4., 2.],
       [4., 2.]])

In [32]:
np.logaddexp(M, a[:, np.newaxis])

array([[1.31326169, 1.31326169],
       [1.69314718, 1.69314718],
       [2.31326169, 2.31326169]])