In [2]:
import numpy as np

In [3]:
np.random.seed(0)

In [4]:
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [5]:
values

array([6, 1, 4, 4, 8])

In [8]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

1.92 s ± 89 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [10]:
print(compute_reciprocals(values))
print(1.0 / values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


In [11]:
%timeit (1.0 / big_array)

2.6 ms ± 190 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [12]:
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [ ]:
# Ufunctions on multidimensional array
x = np.arange()