In [2]:
import numpy as np

In [3]:
# Create a length-10 integer filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
# create a 3x5 floating-point array filled with 1s
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
# create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [6]:
# Create an array filled with a linear sequence
# starting at 0 ending at 20, stepping by 2
# (this is similar to the built in range)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
# Create an array of 5 values evenly spaced between 0 and 10
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [8]:
# create a 4x4array of uniformly distributed
# random values between 0 and 2
np.random.random((4, 4))

array([[0.55743087, 0.11781881, 0.50484137, 0.60209092],
       [0.37336111, 0.96426241, 0.5064002 , 0.91906467],
       [0.60557596, 0.46063477, 0.68804819, 0.80665288],
       [0.95520158, 0.64375761, 0.23803829, 0.75121108]])

In [9]:
# create a 4x4 array of normally distributed random values 
# with a mean 2 and standard deviation 1
np.random.normal(2, 1, (3, 3))

array([[2.43538219, 3.36045117, 2.55879971],
       [3.55849653, 3.68645884, 2.49149262],
       [2.67174718, 2.73470178, 3.58968059]])

array([[0, 4, 2, 6],
       [9, 9, 9, 9],
       [0, 0, 3, 6],
       [9, 1, 9, 4]])

In [11]:
# create a 4x4 identity matrix
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
# create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory loctaion
np.empty(3)

array([1.39440740e-316, 2.12199579e-314, 1.58101007e-322])

In [15]:
# create a 4x4 array of random integers in the interval [0, 10]
x1 = np.random.randint(0, 10, (4, 4))
x1

array([[9, 2, 7, 6],
       [7, 9, 7, 4],
       [9, 8, 5, 9],
       [4, 1, 6, 3]])

In [25]:
# Accessing a multidimensional array
x1[1, -3]

9

In [27]:
x1[0] = 3.14159
x1

array([[3, 3, 3, 3],
       [7, 9, 7, 4],
       [9, 8, 5, 9],
       [4, 1, 6, 3]])